apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
    labels:
        app: hello-world-api
        tier: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: hello-world-api
            tier: backend
    template:
        metadata:
            labels:
                app: hello-world-api
                tier: backend
        spec:
            containers:
                - name: hello-world-api
                  image: fnoah/m300-lb02-api:latest
                  ports:
                      - containerPort: 5000
