apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-deployment
    labels:
        app: hello-world-web
        tier: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: hello-world-web
            tier: frontend
    template:
        metadata:
            labels:
                app: hello-world-web
                tier: frontend
        spec:
            containers:
                - name: hello-world-web
                  image: fnoah/m300-lb02-web:latest
                  ports:
                      - containerPort: 80
