apiVersion: v1
kind: Service
metadata:
    name: m300-lb02-api
    labels:
        app: m300-lb02-api
        tier: backend
spec:
    type: LoadBalancer
    ports:
        - port: 8080
    selector:
        app: m300-lb02-api
        tier: backend
