apiVersion: v1
kind: Service
metadata:
    name: m300-lb02-web
    labels:
        app: m300-lb02-web
        tier: frontend
spec:
    type: LoadBalancer
    ports:
        - port: 80
    selector:
        app: m300-lb02-web
        tier: frontend
